version: '3.3'
services:
  api:
    build:
      context: .
      cache_from:
      - &img_tag telegram-telegram-standup-bot
    image: *img_tag
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - .:/app
